apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "chart.fullname" . }}-warm-up-operation
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  metrics:
  - failureLimit: 0
    name: k6-stack-warm-up
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            metadata:
              labels:
                istio-injection: disabled
                sidecar.istio.io/inject: "false"
            spec:
              containers:
              - image: jjasonhenrique/chip-test:latest
                name: k6-stack-warm-up
              restartPolicy: Never
