app:
  name: linuxtips
  namespace: linuxtips
  createNamespace: true
  iam: ""

  capacity:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
    autoscaling:
      minReplicas: 1
      maxReplicas: 10
    nodepool:
      enabled: true
      name: prometheus

  probes:
    readinessProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
      httpGet:
        path: /
        port: 8080
    livenessProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
      httpGet:
        path: /
        port: 8080
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
      httpGet:
        path: /
        port: 8080

  rollout:
    revisionHistoryLimit: 10
    version: v1
    strategy:
      canary:
        enabled: true
        steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 40
        - pause: {duration: 30s}
        - setWeight: 60
        - pause: {duration: 30s}
        - setWeight: 80
        - pause: {duration: 30s}
        - setWeight: 100
      blueGreen:
        enabled: false
    analysisTemplates:
    - name: 'istio-sucess'
      spec:
        metrics:
        - name: 'sucess-rate'
          interval: 2m
          failureLimit: 0
          successCondition: result[0] >= 0.95
          count: 1
          provider:
            prometheus:
              address: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
              query: |
                sum(irate(
                  istio_requests_total{destination_service=~"linuxtips.linuxtips.svc.cluster.local",response_code!~"5.*"}[5m]
                )) /
                sum(irate(
                  istio_requests_total{destination_service=~"linuxtips.linuxtips.svc.cluster.local"}[5m]
                ))
  
  istio:
    host: linuxtips.jjasonhenrique.com.br
    gateway:
      enabled: true
      protocol: http
      port: 80

    virtualService:
      enabled: true
      http: 
        enabled: true
        port: 80
        retries:
          attempts: 1
          perTryTimeout: 2s
          retryOn: 5xx

  prometheus:
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      port: http
      path: /metrics

  keda:
    enabled: true

    hpaConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 20
        scaleUp:
          stabilizationWindowSeconds: 20
      cooldownPeriod: 30
      pollingInterval: 10

    prometheus:
    # - name: keda-scale-tps
    #   metricName: istio_requests_total
    #   query: "sum(rate(istio_requests_total{destination_service_name=\"linuxtips\"}[1m]))"
    #   serverAddress: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
    #   threshold: "10"

    cron:
    # - name: scale-up
    #   start: 40 14 * * *       
    #   end: 40 18 * * *         
    #   timezone: "America/Sao_Paulo"
    #   desiredReplicas: 20

    memory:
    # - name: memory-high
    #   metricType: Utilization
    #   threshold: 80

    sqs:
    # - name: queue-high
    #   metricType: Utilization
    #   awsRegion: us-east-1
    #   queueURL: https://sqs.us-east-1.amazonaws.com/123456789012/MyQueue
    #   queueLength: 50

    cpu:
    - name: cpu-high
      metricType: Utilization
      threshold: 80

  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent

  
  envs:
  - name: ENV
    value: "dev"
  - name: FOO
    value: "bar"
  
  nodeSelector:
  - label: ""

  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 443

